import os
os.system('pkg install figlet -y')
os.system('clear')
os.system('figlet weeman')
print("weeman is being installed...")
os.system('pkg install zip -y')
os.system('unzip weman.zip')
os.system('mv weman $HOME')
os.system('cd')
os.system('rm -rf weeman')
os.system('cd weman')
os.system('chmod 777 ngrok')
os.system('clear')
os.system('figlet weeman')
print("weeman easy install by Mr. Onion")
print("")
print("GitHub: https://github.com/mronion420")
print("")
print ('Telegram: https://t.me/mronion420')
print("")
print("paste ngrok token Example:")
print("")
print("./ngrok authtoken afhsdjdndkdmdjjdjdhdh")
#os.system('paste ngrok token')
